server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka  

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
      - id: firstModule
        uri: lb://FIRSTSERVICE
        predicates:
        - Path=/firstservice/**
        filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward://fallback/message
      - id: secondModule
        uri: lb://SECONDSERVICE
        predicates:
        - Path=/secondservice/**
        filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward://fallback/message